import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {openApp,state,loadNative,pattern,saveDownload,dropText,E,INPUT} from './browser_common.mjs';
const app=await openApp(),{page}=app,scenarios=[],input=await fs.readFile(INPUT),source=input.toString('utf8');
const pass=name=>{scenarios.push(name);console.log('PASS '+name);};
async function error(){await state(page,'error');assert.equal(await page.locator('#review').isHidden(),true);assert.equal(await page.locator('#download').isDisabled(),true);}
async function importRecipe(value){await page.locator('#recipe-input').setInputFiles({name:'pattern.json',mimeType:'application/json',buffer:Buffer.from(typeof value==='string'?value:JSON.stringify(value))});}
const recipe={weekdays:['friday'],every_weeks:2,anchor:'2027-01-04',start:'2027-01-04',end:'2027-02-28',exclusions:['2027-01-22']};
try{
 assert.equal(await page.locator('html').getAttribute('lang'),'ja');await page.keyboard.press('Tab');assert.equal(await page.locator('.skip').evaluate(n=>n===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('#main').evaluate(n=>n===document.activeElement),true);pass('Japanese default and working keyboard skip link');
 await page.locator('#choose-file').focus();const chosen=page.waitForEvent('filechooser');await page.keyboard.press('Enter');const picker=await chosen;assert.equal(picker.isMultiple(),false);await picker.setFiles(INPUT);await state(page,'loaded');assert.equal(await page.locator('#file-input').inputValue(),'');assert.equal(await page.locator('input[data-resource-id]:checked').count(),0);assert.equal(await page.locator('#download').isDisabled(),true);pass('Keyboard opens a real single-file chooser; import resets resource IDs and same-file input value');
 await page.locator('#preview').click();await error();await page.locator('#lang-en').click();assert.match(await page.locator('#error').textContent(),/Cannot process/);await pattern(page);assert.equal(await page.locator('#addition-count').textContent(),'5');assert.equal(await page.locator('#covered-count').textContent(),'1');assert.equal(await page.locator('#excluded-count').textContent(),'2');assert.equal(await page.locator('#total-count').textContent(),'7');assert.equal(await page.locator('#review-rows tr').count(),8);assert.equal(await page.locator('#download').isDisabled(),true);pass('Explicit A/B selection previews all eight date/resource rows and exact five additions');
 await saveDownload(page,'#report','ui-unacknowledged-review.json');const review=JSON.parse(await fs.readFile(path.join(E,'ui-unacknowledged-review.json'),'utf8'));assert.deepEqual(review.selected_resource_ids,['0','1']);assert.deepEqual(review.candidate_dates.map(r=>r.date),['2027-01-08','2027-01-22','2027-02-05','2027-02-19']);assert.equal(review.additions.length,5);pass('Complete review JSON is available before acknowledgment and contains every candidate');
 await page.locator('#ack').focus();await page.keyboard.press('Space');await saveDownload(page,'#download','ui-first.gan');await saveDownload(page,'#download','ui-repeat.gan');assert.deepEqual(await fs.readFile(path.join(E,'ui-first.gan')),await fs.readFile(path.join(E,'ui-repeat.gan')));await saveDownload(page,'#recipe','ui-recipe.json');assert.deepEqual(JSON.parse(await fs.readFile(path.join(E,'ui-recipe.json'),'utf8')),recipe);pass('Acknowledged actual downloads repeat deterministically and recipe omits resource IDs');
 await loadNative(page,path.join(E,'ui-first.gan'));await pattern(page);assert.equal(await page.locator('#addition-count').textContent(),'0');assert.equal(await page.locator('#no-op').isVisible(),true);await page.locator('#ack').check();await saveDownload(page,'#download','ui-noop.gan');assert.deepEqual(await fs.readFile(path.join(E,'ui-noop.gan')),await fs.readFile(path.join(E,'ui-first.gan')));pass('Reimporting prepared output produces a genuine byte-identical no-op');
 await loadNative(page);await pattern(page);await page.locator('#ack').check();await page.locator('#exclusions').fill('2027-01-22,2027-02-19');assert.equal(await page.locator('#review').isHidden(),true);assert.equal(await page.locator('#ack').isChecked(),false);assert.equal(await page.locator('#download').isDisabled(),true);await page.locator('#preview').click();await state(page,'ready');assert.equal(await page.locator('#addition-count').textContent(),'3');pass('Editing an exclusion invalidates output and acknowledgment before recalculation');
 await importRecipe(recipe);await state(page,'loaded');assert.equal(await page.locator('input[data-resource-id]:checked').count(),0);assert.equal(await page.locator('#review').isHidden(),true);assert.equal(await page.locator('#recipe-input').inputValue(),'');await pattern(page);await loadNative(page);assert.equal(await page.locator('input[data-resource-id]:checked').count(),0);assert.equal(await page.locator('#review').isHidden(),true);pass('Recipe and repeated project imports require fresh resource selection');
 await importRecipe({...recipe,resource_ids:['0']});await error();await importRecipe('{"weekdays":["friday"],"weekdays":["monday"]}');await error();pass('Resource-bearing and duplicate-key recipes reject without stale output');
 await loadNative(page);await pattern(page);await page.locator('#anchor').fill('2027-01-05');await page.locator('#preview').click();await error();await page.locator('#anchor').fill('1899-12-25');await page.locator('#preview').click();await error();await page.locator('#anchor').fill('2027-01-04');await page.locator('#end').fill('2028-01-05');await page.locator('#preview').click();await error();pass('Non-Monday anchor, unsupported years and excessive date windows reject');
 await page.evaluate(()=>{globalThis.__savedWorker=globalThis.Worker;globalThis.Worker=class{constructor(){throw new Error('Synthetic worker startup failure');}};});await dropText(page,source);await error();assert.match(await page.locator('#error').textContent(),/Synthetic worker startup failure/);await page.evaluate(()=>globalThis.Worker=globalThis.__savedWorker);await loadNative(page);pass('Worker startup failure blocks output and a later valid import recovers');
 await dropText(page,'<'+ 'x'.repeat(1_000_000) +'/>');await error();assert.ok((await page.locator('#error').textContent()).length<2200);pass('Huge malformed names cannot create an unbounded error display');
 const hostile=source.replace('name="RESOURCEA"','name="&lt;img src=&quot;https://example.invalid/never&quot; onerror=&quot;globalThis.__executed=true&quot;&gt;"').replace('webLink="http://"','webLink="https://example.invalid/not-followed"');await dropText(page,hostile);await state(page,'loaded');await pattern(page);assert.equal(await page.locator('#resources img,#review-rows img').count(),0);assert.equal(await page.evaluate(()=>globalThis.__executed),undefined);assert.match(await page.locator('#resources').textContent(),/<img src=/);pass('Resource names and links remain inert literal data');
 for(const malformed of [source.replace('version="3.4.3396"','version="3.3.3316"'),source.replace('<project ','<!DOCTYPE project [<!ENTITY x "bad">]><project '),source.replace('resourceid="0"','resourceid="999"'),source.replace('id="2" name="RESOURCEC"','id="1" name="RESOURCEC"')]){await dropText(page,malformed);await error();}pass('Unsupported version, DTD, dangling reference and duplicate IDs reject whole inputs');
 await page.evaluate(()=>{const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){if(this.name==='oversize.gan')globalThis.__oversizeRead=true;if(this.name==='older.gan'||this.name==='older.json'){globalThis.__delayedStarted=true;await new Promise(resolve=>setTimeout(resolve,350));}return original.call(this);};globalThis.__oversizeRead=false;globalThis.__delayedStarted=false;});
 await page.evaluate(()=>{const d=new DataTransfer();d.items.add(new File([new Uint8Array(10*1024*1024+1)],'oversize.gan'));document.getElementById('drop-zone').dispatchEvent(new DragEvent('drop',{dataTransfer:d,bubbles:true}));});await error();assert.equal(await page.evaluate(()=>globalThis.__oversizeRead),false);pass('Ten-MiB project bound is enforced before reading bytes');
 await dropText(page,source,'wrong.txt');await error();await page.evaluate(()=>{const d=new DataTransfer();d.items.add(new File(['a'],'one.gan'));d.items.add(new File(['b'],'two.gan'));document.getElementById('drop-zone').dispatchEvent(new DragEvent('drop',{dataTransfer:d,bubbles:true}));});await error();await page.locator('#recipe-input').setInputFiles({name:'large.json',mimeType:'application/json',buffer:Buffer.alloc(65537,32)});await error();pass('Wrong file kind, multiple projects and oversized recipes fail explicitly');
 await dropText(page,source.replace('RESOURCEA','OLDASYNC'),'older.gan');await page.waitForFunction(()=>globalThis.__delayedStarted);await loadNative(page);await page.waitForTimeout(430);assert.equal(await page.locator('#resources').textContent().then(x=>x.includes('OLDASYNC')),false);pass('A newer file wins over an older delayed read');
 await page.evaluate(()=>globalThis.__delayedStarted=false);await dropText(page,source,'older.gan');await page.waitForFunction(()=>globalThis.__delayedStarted);await page.locator('#clear').click();await page.waitForTimeout(430);await state(page,'empty');assert.equal(await page.locator('#workbench').isHidden(),true);pass('Clear cancels pending file reads without resurrecting the project');
 await loadNative(page);await page.evaluate(()=>{const n=document.getElementById('file-input');n.value='';n.dispatchEvent(new Event('change',{bubbles:true}));});await state(page,'empty');assert.equal(await page.locator('#resources input').count(),0);pass('An explicitly dispatched empty file change clears stale state without claiming picker cancellation');
 await loadNative(page);await pattern(page);await page.evaluate(()=>{const NativeWorker=globalThis.Worker;globalThis.Worker=class extends NativeWorker{postMessage(...args){if(globalThis.__delayWorker){globalThis.__workerStarted=true;setTimeout(()=>{if(!this.__stopped)super.postMessage(...args);},350);}else super.postMessage(...args);}terminate(){this.__stopped=true;globalThis.__workerTerminated=(globalThis.__workerTerminated||0)+1;return super.terminate();}};globalThis.__delayWorker=true;globalThis.__workerStarted=false;globalThis.__workerTerminated=0;});await page.locator('#preview').click();await page.waitForFunction(()=>globalThis.__workerStarted);await page.locator('#exclusions').fill('2027-01-22,2027-02-19');await page.evaluate(()=>globalThis.__delayWorker=false);await page.waitForTimeout(430);assert.equal(await page.locator('#review').isHidden(),true);assert.equal(await page.locator('#download').isDisabled(),true);assert.ok(await page.evaluate(()=>globalThis.__workerTerminated>0));await page.locator('#preview').click();await state(page,'ready');assert.equal(await page.locator('#addition-count').textContent(),'3');pass('A setting change terminates an in-flight worker preview before stale output');
 await page.evaluate(()=>{globalThis.__delayWorker=true;globalThis.__workerStarted=false;globalThis.__workerTerminated=0;});await dropText(page,source);await page.waitForFunction(()=>globalThis.__workerStarted);await page.locator('#clear').click();await page.evaluate(()=>globalThis.__delayWorker=false);await page.waitForTimeout(430);await state(page,'empty');assert.ok(await page.evaluate(()=>globalThis.__workerTerminated>0));pass('Clear terminates a pending parser worker and remains responsive');
 await loadNative(page);await pattern(page);
 await page.evaluate(()=>{const Previous=globalThis.Worker;globalThis.Worker=class extends Previous{set onmessage(handler){this.__consumer=handler;super.onmessage=event=>{if(globalThis.__holdWorkerResult){globalThis.__heldWorkerResult=()=>handler(event);}else handler(event);};}get onmessage(){return this.__consumer;}};globalThis.__holdWorkerResult=true;globalThis.__heldWorkerResult=null;});await page.locator('#preview').click();await page.waitForFunction(()=>globalThis.__heldWorkerResult!==null);await page.locator('#exclusions').fill('2027-01-22,2027-02-19');await page.evaluate(()=>{globalThis.__holdWorkerResult=false;globalThis.__heldWorkerResult();});await page.waitForTimeout(100);assert.equal(await page.locator('#review').isHidden(),true);assert.equal(await page.locator('#download').isDisabled(),true);pass('A queued real worker result from a prior revision cannot restore stale output');
 await page.evaluate(()=>globalThis.__delayedStarted=false);await page.locator('#recipe-input').setInputFiles({name:'older.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...recipe,anchor:'2027-01-11'}))});await page.waitForFunction(()=>globalThis.__delayedStarted);await page.locator('#anchor').fill('2027-01-18');await page.waitForTimeout(430);assert.equal(await page.locator('#anchor').inputValue(),'2027-01-18');pass('A later form edit wins over a delayed recipe import');
 await loadNative(page);await pattern(page);await page.locator('#cadence').selectOption('1');await page.locator('#end').fill('2027-04-13');for(const day of ['monday','tuesday','wednesday','thursday','friday','saturday','sunday'])await page.locator('#weekday-'+day).check();await page.locator('#select-all').click();await page.locator('#preview').click();await state(page,'ready');assert.equal(await page.locator('#review-rows tr').count(),60);assert.match(await page.locator('#page-range').textContent(),/1–60 of 300/);await page.locator('#next').click();assert.match(await page.locator('#page-range').textContent(),/61–120 of 300/);await saveDownload(page,'#report','ui-paginated-review.json');assert.equal(JSON.parse(await fs.readFile(path.join(E,'ui-paginated-review.json'),'utf8')).candidates_by_resource.length,300);pass('Pagination exposes every row while the complete JSON retains all 300 entries');
 const many=source.replace('</resources>',Array.from({length:98},(_,i)=>`<resource id="${i+3}" name="Extra${i}" function="Default:0" contacts="" phone=""/>`).join('')+'</resources>');await dropText(page,many);await state(page,'loaded');assert.equal(await page.locator('#resources input').count(),100);await page.locator('#resource-next').click();assert.equal(await page.locator('#resources input').count(),1);await page.locator('#resource-search').fill('Extra97');assert.equal(await page.locator('#resources input').count(),1);await page.locator('#select-all').click();await error();assert.match(await page.locator('#error').textContent(),/100/);pass('Resource browsing stays bounded and selecting more than 100 fails before output');
 await loadNative(page);await pattern(page);await page.locator('#lang-en').click();await page.screenshot({path:path.join(E,'ui-en-desktop.png'),fullPage:true});await page.screenshot({path:path.join(E,'ui-en-desktop-top.png')});await page.locator('#review').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(E,'ui-en-desktop-review.png')});await page.locator('#lang-ja').click();await page.screenshot({path:path.join(E,'ui-ja-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(E,'ui-ja-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#lang-en').click();await page.screenshot({path:path.join(E,'ui-en-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('#table-scroll').evaluate(n=>n.scrollLeft=n.scrollWidth);const edge=await page.locator('#table-scroll').evaluate(n=>{const b=n.getBoundingClientRect(),c=n.querySelector('thead th:last-child').getBoundingClientRect();return {left:b.left,right:b.right,cellLeft:c.left,cellRight:c.right,overflow:n.scrollWidth>n.clientWidth};});assert.equal(edge.overflow,true);assert.ok(edge.cellLeft>=edge.left-1&&edge.cellRight<=edge.right+1);await page.locator('#table-scroll').evaluate(n=>window.scrollTo(0,n.getBoundingClientRect().top+scrollY-80));await page.screenshot({path:path.join(E,'ui-en-mobile-table-end.png')});pass('JA/EN desktop and 390px views retain complete controls and the rightmost table column');
 await page.evaluate(()=>document.documentElement.style.fontSize='200%');await page.screenshot({path:path.join(E,'ui-en-mobile-large-text.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.ok(await page.locator('#preview').evaluate(n=>parseFloat(getComputedStyle(n).fontSize)>=30));await page.locator('#preview').scrollIntoViewIfNeeded();await page.locator('#preview').click();await state(page,'ready');assert.equal(await page.locator('#addition-count').textContent(),'5');await page.evaluate(()=>document.documentElement.style.fontSize='');pass('Two-hundred-percent root text remains readable, contained and operable on mobile');
 await page.setViewportSize({width:1440,height:1000});for(const language of ['en','ja']){await page.emulateMedia({media:'screen'});await page.locator('#lang-'+language).click();await page.emulateMedia({media:'print'});assert.equal(await page.locator('#review-rows tr').count(),8);assert.equal(await page.locator('#print-scope').isVisible(),true);assert.match(await page.locator('#print-scope').textContent(),/3\.4\.3396 Beta VI/);assert.match(await page.locator('#print-scope').textContent(),language==='en'?/No scheduling/:/スケジューリング/);await page.locator('#hash-details').evaluate(n=>n.open=true);const stem=language==='en'?'ui-print':'ui-print-ja';await page.screenshot({path:path.join(E,stem+'.png'),fullPage:true});await page.pdf({path:path.join(E,stem+'.pdf'),format:'A4',landscape:true,printBackground:true});}await page.emulateMedia({media:'screen'});pass('JA/EN print includes all eight fixture rows, summary, source/output hashes and scope');
 assert.deepEqual(app.errors,[]);assert.deepEqual(app.network,[]);assert.deepEqual(await fs.readFile(INPUT),input);pass('Packaged offline file-protocol app produces no console errors or network requests and leaves input intact');
 await fs.writeFile(path.join(E,'browser-ui-result.json'),JSON.stringify({status:'pass',scenarios,sourceSha256:crypto.createHash('sha256').update(input).digest('hex'),consoleErrors:app.errors,networkRequests:app.network},null,2)+'\n');
}catch(error){await page.screenshot({path:path.join(E,'FAILED-browser-test.png'),fullPage:true});throw error;}finally{await app.browser.close();}
